{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-httproute
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gatewayRef.name }}
      {{- if .Values.httpRoute.gatewayRef.namespace }}
      namespace: {{ .Values.httpRoute.gatewayRef.namespace }}
      {{- end }}
      {{- if .Values.httpRoute.gatewayRef.sectionName }}
      sectionName: {{ .Values.httpRoute.gatewayRef.sectionName }}
      {{- end }}
  hostnames:
    - {{ .Values.httpRoute.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /web-api
      backendRefs:
        - name: {{ include "bymseread.service.name" . }}
          port: {{ .Values.service.service.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "bymseread.webclientapp.name" . }}
          port: {{ .Values.service.webClientApp.port }}
{{- end }}
